export const CLASSES_FETCH_DATA = 'CLASSES_FETCH_DATA';
export const CLASSES_SET_DATA = 'CLASSES_SET_DATA';
export const FETCH_CLASS_STUDENTS_ROLLED_UP = 'FETCH_CLASS_STUDENTS_ROLLED_UP';
export const SET_CLASS_STUDENTS_ROLLED_UP = 'SET_CLASS_STUDENTS_ROLLED_UP';
export const FETCH_CLASS_STUDENTS_BY_LESSON_ID = 'FETCH_CLASS_STUDENTS_BY_LESSON_ID';
export const CLASSES_DEFAULT = 'CLASSES_DEFAULT';
