export const LESSON_FETCH_DATA = 'LESSON_FETCH_DATA';
export const LESSON_SET_DATA = 'LESSON_SET_DATA';
export const LESSON_CREATE = 'LESSON_CREATE';
export const FETCH_LESSON_STUDENTS_ROLLED_UP = 'FETCH_LESSON_STUDENTS_ROLLED_UP';
export const SET_LESSON_STUDENTS_ROLLED_UP = 'SET_LESSON_STUDENTS_ROLLED_UP';
export const FETCH_CLASS_BY_LESSON_ID = 'FETCH_CLASS_BY_LESSON_ID';
export const SET_CLASS = 'SET_CLASS_BY_LESSON_ID';
export const LESSON_DEFAULT = 'LESSON_DEFAULT';